version: '3'
services:
  elasticsearch-hot:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: hot
    command: ["sh", "-c", "/usr/share/elasticsearch/bin/elasticsearch-plugin install repository-s3 -s --batch && /usr/local/bin/docker-entrypoint.sh"]
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=$CERTS_DIR/elasticsearch-hot/elasticsearch-hot.key
      - xpack.security.http.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
      - xpack.security.http.ssl.certificate=$CERTS_DIR/elasticsearch-hot/elasticsearch-hot.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate 
      - xpack.security.transport.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
      - xpack.security.transport.ssl.certificate=$CERTS_DIR/elasticsearch-hot/elasticsearch-hot.crt
      - xpack.security.transport.ssl.key=$CERTS_DIR/elasticsearch-hot/elasticsearch-hot.key
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
    volumes:
      - $PWD/hot/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml  
      - $PWD/hot/elasticsearch.keystore:/usr/share/elasticsearch/config/elasticsearch.keystore  
      - $PWD:/usr/share/elasticsearch/config/docker_host
      - certs:$CERTS_DIR
    networks:
      - esnet

  elasticsearch-warm:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: warm
    command: ["sh", "-c", "/usr/share/elasticsearch/bin/elasticsearch-plugin install repository-s3 -s --batch && /usr/local/bin/docker-entrypoint.sh"]
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=$CERTS_DIR/elasticsearch-warm/elasticsearch-warm.key
      - xpack.security.http.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
      - xpack.security.http.ssl.certificate=$CERTS_DIR/elasticsearch-warm/elasticsearch-warm.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate 
      - xpack.security.transport.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
      - xpack.security.transport.ssl.certificate=$CERTS_DIR/elasticsearch-warm/elasticsearch-warm.crt
      - xpack.security.transport.ssl.key=$CERTS_DIR/elasticsearch-warm/elasticsearch-warm.key
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9201:9201
    volumes:
      - $PWD/warm/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml  
      - $PWD/warm/elasticsearch.keystore:/usr/share/elasticsearch/config/elasticsearch.keystore  
      - $PWD:/usr/share/elasticsearch/config/docker_host
      - certs:$CERTS_DIR
    networks:
      - esnet

  elasticsearch-cold:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    container_name: cold
    command: ["sh", "-c", "/usr/share/elasticsearch/bin/elasticsearch-plugin install repository-s3 -s --batch && /usr/local/bin/docker-entrypoint.sh"]
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=$CERTS_DIR/elasticsearch-cold/elasticsearch-cold.key
      - xpack.security.http.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
      - xpack.security.http.ssl.certificate=$CERTS_DIR/elasticsearch-cold/elasticsearch-cold.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.verification_mode=certificate 
      - xpack.security.transport.ssl.certificate_authorities=$CERTS_DIR/ca/ca.crt
      - xpack.security.transport.ssl.certificate=$CERTS_DIR/elasticsearch-cold/elasticsearch-cold.crt
      - xpack.security.transport.ssl.key=$CERTS_DIR/elasticsearch-cold/elasticsearch-cold.key
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9202:9202
    volumes:
      - $PWD/cold/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml  
      - $PWD/cold/elasticsearch.keystore:/usr/share/elasticsearch/config/elasticsearch.keystore  
      - $PWD:/usr/share/elasticsearch/config/docker_host
      - certs:$CERTS_DIR
    networks:
      - esnet
 
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    container_name: kibana
    ports:
      - "5601:5601"
    networks:
      - esnet
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
      - certs:$CERTS_DIR
    depends_on:
      - elasticsearch-hot

  minio:
    image: minio/minio
    container_name: minio 
    command: server /data
    environment:
      - "MINIO_ACCESS_KEY=AKIAIOSFODNN7EXAMPLE"
      - "MINIO_SECRET_KEY=wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
    ports:
      - 9000:9000
    volumes:
      - /data:/home/jakelandis/workspace/data/minio
    networks:
      - esnet

volumes: {"certs"}

networks:
  esnet:
